#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend kanayo.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 151042-web-01 52.86.96.101:80
        server 151042-web-02 52.72.73.177:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
